# Generated by Django 4.2.5 on 2023-12-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('achievement_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_gained', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='users', to='user_api.achievement'),
        ),
    ]
