# Generated by Django 4.2.5 on 2023-12-08 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_achievement_appuser_age_appuser_achievements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='user_id',
            new_name='id',
        ),
    ]
