# Generated by Django 4.2.5 on 2023-12-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_appuser_is_active_appuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
