# Generated by Django 4.2.5 on 2023-12-09 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0008_alter_article_content_alter_course_about_and_more'),
        ('quiz', '0004_question_course_alter_answer_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='theory.course'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='theory.course')),
                ('questions', models.ManyToManyField(related_name='tests', to='quiz.question')),
            ],
        ),
    ]
