# Generated by Django 4.2.5 on 2023-12-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('theory_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(default='text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='article_images/')),
                ('category', models.CharField(choices=[('news', 'News'), ('lecture', 'Lecture'), ('theory', 'Theory'), ('article', 'Article')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
