# Generated by Django 4.2.5 on 2023-12-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0002_theory_sub_title_alter_theory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory',
            name='category',
            field=models.CharField(choices=[('news', 'News'), ('lecture', 'Lecture'), ('theory', 'Theory'), ('article', 'Article'), ('course', 'Course')], max_length=10),
        ),
    ]
