# Generated by Django 4.2.5 on 2023-12-09 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0003_alter_theory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theory',
            old_name='sub_title',
            new_name='about',
        ),
    ]
