# Generated by Django 4.2.5 on 2023-12-09 09:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0005_topic_theory_price_theory_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theory',
            name='topics',
        ),
        migrations.AddField(
            model_name='theory',
            name='themes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
