# Generated by Django 4.2.5 on 2023-12-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0007_article_course_lecture_delete_theory_delete_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='about',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
